CustomisableFormsApp/CustomisableFormsApp/Controllers/TemplateController.cs
using CustomisableFormsApp.Data;
using CustomisableFormsApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CustomisableFormsApp.Controllers
{
    public class TemplateController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        public TemplateController(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                var applicationDbContext = _db.Templates.Include(d => d.User);
                return View(await applicationDbContext.ToListAsync());
            }
            else if (User.IsInRole("Candidate") || User.IsInRole("Creator"))
            {
                var applicationDbContext = from c in _db.Templates
                                           select c;
                applicationDbContext = applicationDbContext.Where(a => a.USER_ID == User.FindFirstValue(ClaimTypes.NameIdentifier));
                return View(await applicationDbContext.Include(d => d.User).ToListAsync());
            }
            else
            {
                var applicationDbContext = _db.Templates.Include(d => d.User);
                return View(await applicationDbContext.ToListAsync());
            }
        }

        [Authorize(Roles = "Admin, Creator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Creator")]
        public IActionResult Create(Template obj)
        {
            if (ModelState.IsValid)
            {
                _db.Templates.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Form created successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            ///////////GET CANDIDATE NAME/////////
            var template = _db.Templates.Include(t => t.User_CANDIDATE).FirstOrDefault(t => t.ID == id);

            if (template == null)
            {
                return NotFound();
            }

            // Check if the user is logged in
            if (template.User_CANDIDATE != null && User.Identity != null && User.Identity.IsAuthenticated)
            {
                ViewData["UserName"] = template.User_CANDIDATE.UserName;
            }
            else
            {
                ViewData["UserName"] = "None";
            }
            ///////////---GET CANDIDATE NAME---/////////

            if (id == null || id == 0)
            {
                return NotFound();
            }
            Template? TemplateFromDb = _db.Templates.Find(id);
            //Category? categoryFromDb1 = _db.Categories.FirstOrDefault(u=>u.Id==id);
            //Category? categoryFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();

            if (TemplateFromDb == null)
            {
                return NotFound();
            }
            return View(TemplateFromDb);
        }

        [HttpPost]
        //public IActionResult Edit(Template obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Templates.Update(obj);
        //        _db.SaveChanges();
        //        TempData["success"] = "Form updated successfully";
        //        return RedirectToAction("Index");
        //    }
        //    return View();

        //}
        [Authorize(Roles = "Admin, Creator, Candidate")]
        public IActionResult Edit(Template obj, IFormCollection form)
        {
            if (User.IsInRole("Admin"))
            {
                var template = _db.Templates.Find(obj.ID);
                if (template is not null)
                {
                    template.TITLE = obj.TITLE;
                    template.DESCRIPTION = obj.DESCRIPTION;

                    for (int i = 1; i <= 50; i++)
                    {
                        var questionProp = $"CUSTOM_STRING{i}_QUESTION";
                        var answerProp = $"CUSTOM_STRING{i}_ANSWER";

                        // Get values from form and assign to template
                        var questionValue = form[questionProp].ToString();
                        var answerValue = form[answerProp].ToString();

                        template.GetType().GetProperty(questionProp)?.SetValue(template, questionValue);
                        template.GetType().GetProperty(answerProp)?.SetValue(template, answerValue);
                    }

                    //This code also works

                    //template.CUSTOM_STRING1_QUESTION = obj.CUSTOM_STRING1_QUESTION;
                    //template.CUSTOM_STRING1_ANSWER = obj.CUSTOM_STRING1_ANSWER;
                    //template.CUSTOM_STRING2_QUESTION = obj.CUSTOM_STRING2_QUESTION;
                    //template.CUSTOM_STRING2_ANSWER = obj.CUSTOM_STRING2_ANSWER;
                    //template.CUSTOM_STRING3_QUESTION = obj.CUSTOM_STRING3_QUESTION;
                    //template.CUSTOM_STRING3_ANSWER = obj.CUSTOM_STRING3_ANSWER;
                    //template.CUSTOM_STRING4_QUESTION = obj.CUSTOM_STRING4_QUESTION;
                    //template.CUSTOM_STRING4_ANSWER = obj.CUSTOM_STRING4_ANSWER;
                    //template.CUSTOM_STRING5_QUESTION = obj.CUSTOM_STRING5_QUESTION;
                    //template.CUSTOM_STRING5_ANSWER = obj.CUSTOM_STRING5_ANSWER;
                    //template.CUSTOM_STRING6_QUESTION = obj.CUSTOM_STRING6_QUESTION;
                    //template.CUSTOM_STRING6_ANSWER = obj.CUSTOM_STRING6_ANSWER;
                    //template.CUSTOM_STRING7_QUESTION = obj.CUSTOM_STRING7_QUESTION;
                    //template.CUSTOM_STRING7_ANSWER = obj.CUSTOM_STRING7_ANSWER;
                    //template.CUSTOM_STRING8_QUESTION = obj.CUSTOM_STRING8_QUESTION;
                    //template.CUSTOM_STRING8_ANSWER = obj.CUSTOM_STRING8_ANSWER;
                    //template.CUSTOM_STRING9_QUESTION = obj.CUSTOM_STRING9_QUESTION;
                    //template.CUSTOM_STRING9_ANSWER = obj.CUSTOM_STRING9_ANSWER;
                    //template.CUSTOM_STRING10_QUESTION = obj.CUSTOM_STRING10_QUESTION;
                    //template.CUSTOM_STRING10_ANSWER = obj.CUSTOM_STRING10_ANSWER;
                    //template.CUSTOM_STRING11_QUESTION = obj.CUSTOM_STRING11_QUESTION;
                    //template.CUSTOM_STRING11_ANSWER = obj.CUSTOM_STRING11_ANSWER;
                    //template.CUSTOM_STRING12_QUESTION = obj.CUSTOM_STRING12_QUESTION;
                    //template.CUSTOM_STRING12_ANSWER = obj.CUSTOM_STRING12_ANSWER;
                    //template.CUSTOM_STRING13_QUESTION = obj.CUSTOM_STRING13_QUESTION;
                    //template.CUSTOM_STRING13_ANSWER = obj.CUSTOM_STRING13_ANSWER;
                    //template.CUSTOM_STRING14_QUESTION = obj.CUSTOM_STRING14_QUESTION;
                    //template.CUSTOM_STRING14_ANSWER = obj.CUSTOM_STRING14_ANSWER;
                    //template.CUSTOM_STRING15_QUESTION = obj.CUSTOM_STRING15_QUESTION;
                    //template.CUSTOM_STRING15_ANSWER = obj.CUSTOM_STRING15_ANSWER;
                    //template.CUSTOM_STRING16_QUESTION = obj.CUSTOM_STRING16_QUESTION;
                    //template.CUSTOM_STRING16_ANSWER = obj.CUSTOM_STRING16_ANSWER;
                    //template.CUSTOM_STRING17_QUESTION = obj.CUSTOM_STRING17_QUESTION;
                    //template.CUSTOM_STRING17_ANSWER = obj.CUSTOM_STRING17_ANSWER;
                    //template.CUSTOM_STRING18_QUESTION = obj.CUSTOM_STRING18_QUESTION;
                    //template.CUSTOM_STRING18_ANSWER = obj.CUSTOM_STRING18_ANSWER;
                    //template.CUSTOM_STRING19_QUESTION = obj.CUSTOM_STRING19_QUESTION;
                    //template.CUSTOM_STRING19_ANSWER = obj.CUSTOM_STRING19_ANSWER;
                    //template.CUSTOM_STRING20_QUESTION = obj.CUSTOM_STRING20_QUESTION;
                    //template.CUSTOM_STRING20_ANSWER = obj.CUSTOM_STRING20_ANSWER;
                    //template.CUSTOM_STRING21_QUESTION = obj.CUSTOM_STRING21_QUESTION;
                    //template.CUSTOM_STRING21_ANSWER = obj.CUSTOM_STRING21_ANSWER;
                    //template.CUSTOM_STRING22_QUESTION = obj.CUSTOM_STRING22_QUESTION;
                    //template.CUSTOM_STRING22_ANSWER = obj.CUSTOM_STRING22_ANSWER;
                    //template.CUSTOM_STRING23_QUESTION = obj.CUSTOM_STRING23_QUESTION;
                    //template.CUSTOM_STRING23_ANSWER = obj.CUSTOM_STRING23_ANSWER;
                    //template.CUSTOM_STRING24_QUESTION = obj.CUSTOM_STRING24_QUESTION;
                    //template.CUSTOM_STRING24_ANSWER = obj.CUSTOM_STRING24_ANSWER;
                    //template.CUSTOM_STRING25_QUESTION = obj.CUSTOM_STRING25_QUESTION;
                    //template.CUSTOM_STRING25_ANSWER = obj.CUSTOM_STRING25_ANSWER;
                    //template.CUSTOM_STRING26_QUESTION = obj.CUSTOM_STRING26_QUESTION;
                    //template.CUSTOM_STRING26_ANSWER = obj.CUSTOM_STRING26_ANSWER;
                    //template.CUSTOM_STRING27_QUESTION = obj.CUSTOM_STRING27_QUESTION;
                    //template.CUSTOM_STRING27_ANSWER = obj.CUSTOM_STRING27_ANSWER;
                    //template.CUSTOM_STRING28_QUESTION = obj.CUSTOM_STRING28_QUESTION;
                    //template.CUSTOM_STRING28_ANSWER = obj.CUSTOM_STRING28_ANSWER;
                    //template.CUSTOM_STRING29_QUESTION = obj.CUSTOM_STRING29_QUESTION;
                    //template.CUSTOM_STRING29_ANSWER = obj.CUSTOM_STRING29_ANSWER;

CustomisableFormsApp/CustomisableFormsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineCustomisableForms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomisableFormsApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Template" asp-action="Index">CustomisableForms</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="Index">Forms</a>
                        </li> 
                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UserList">UserList</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OnlineCustomisableForms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CustomisableFormsApp/CustomisableFormsApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}